name: Build & Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REPO: pedrolongoo  # seu usuário Docker Hub

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: bff
            path: ./bff
          - name: svc-consultas
            path: ./svc-consultas
          - name: svc-tutors
            path: ./svc-tutors

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.name }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.path }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/${{ matrix.name }}:latest
            ${{ env.DOCKER_REPO }}/${{ matrix.name }}:${{ github.sha }}
